# Conexao com o banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/esteticadesk_db
spring.datasource.username=postgres
spring.datasource.password=Sync@933

# Servidor web
server.port=8080

# Configuracao do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Thymeleaf
spring.thymeleaf.cache=false

# Configuracao do Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration